### ISSUE TITLE
Breaking Living Off The Land Trait

### ISSUE THREAD

**Issue by KailJaxxon** [jonathan-robertson/gmo-farming#69]
I am having only a single problem with the gmo-farming mod. It is that it is changing the Living off the land trait breaking any other mod that uses that particular trait. Is there a way I can change it to not alter this trait so that the other mods will function? I really would like to use this mod if at all possible, thanks.

**Comment by jonathan-robertson** [comment]
Hello Kail, thanks for reaching out!

The short answer is: Yes, I plan to do this and think it will help in your situation as well.

Since [A21 is planning to no longer have any recipe unlocks via skills](https://community.7daystodie.com/topic/28129-alpha-21-dev-diary/), I also plan to update this mod in the near future so that it no longer relies at all on Living off the Land.

As for when I'll have time to update it... hopefully soon 😄 

Since this will be a breaking change, I'll be releasing it as version 2.0.0 and will let you know when it's ready to go.

**Comment by jonathan-robertson** [comment]
@KailJaxxon A [new update is available that no longer adjusts Living off the Land](https://github.com/jonathan-robertson/gmo-farming/releases/tag/2.0.0)! 🎉
Please let me know if you encounter any issues with it 😄

**Comment by KailJaxxon** [comment]
@jonathan-robertson Thanks, that was fast. We all love the mod, looking forward to other mods you happen to whip up. ;)
